# AeroSpace Configuration File
#
# Enhanced with smooth, minimal animations and Hyprland-inspired workflow
# For more details on available commands and settings, see:
# https://nikitabobko.github.io/AeroSpace/guide
# https://nikitabobko.github.io/AeroSpace/commands

#─────────────────────────────────────────────────────────────────────
# Global Settings
#─────────────────────────────────────────────────────────────────────

# Start Aerospace automatically when the user logs in.
start-at-login = true

# Commands to run after the macOS user session starts and AeroSpace is running.
after-login-command = []

# Commands to run immediately after AeroSpace successfully starts up.
after-startup-command = ['exec-and-forget barik']

# Notify barik about workspace changes for smooth status bar updates
exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'pkill -SIGUSR1 barik 2>/dev/null || true'
]

# ─────────────────────────────────────────────────────────────────────
# Normalization Settings - Hyprland-like Tiling Behavior
# ─────────────────────────────────────────────────────────────────────

# Flatten containers for cleaner layout tree
enable-normalization-flatten-containers = true

# Opposite orientation creates spiral-like tiling (Hyprland-style)
enable-normalization-opposite-orientation-for-nested-containers = true

#─────────────────────────────────────────────────────────────────────
# Default Layout & Behavior Settings
#─────────────────────────────────────────────────────────────────────

non-empty-workspaces-root-containers-layout-on-startup = 'tiles'

# Tiles layout for automatic spiral-like tiling pattern
default-root-container-layout = 'tiles'

# Auto orientation based on monitor dimensions
default-root-container-orientation = 'auto'

accordion-padding = 30

# Key mapping preset
key-mapping.preset = 'qwerty'

# Smooth mouse following for enhanced UX (Hyprland-like)
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# ─────────────────────────────────────────────────────────────────────
# Visual Settings - Minimal, Clean Aesthetics
# ─────────────────────────────────────────────────────────────────────

[gaps]
  # Balanced gaps for clean minimal look
  inner.horizontal = 12
  inner.vertical   = 12
  outer.left       = 12
  outer.bottom     = 12
  outer.top        = [{ monitor.'^built-in.*$' = 12 }, 64]
  outer.right      = 12

# ─────────────────────────────────────────────────────────────────────
# Keybindings - Hyprland-Inspired
# ─────────────────────────────────────────────────────────────────────

[mode.main.binding]
  # Workspace navigation (Hyprland-style with alt)
  alt-1 = 'workspace 1'
  alt-2 = 'workspace 2'
  alt-3 = 'workspace 3'
  alt-4 = 'workspace 4'
  alt-5 = 'workspace 5'
  alt-6 = 'workspace 6'
  alt-7 = 'workspace 7'
  alt-8 = 'workspace 8'
  alt-9 = 'workspace 9'

  # Window movement to workspaces
  alt-shift-1 = 'move-node-to-workspace 1'
  alt-shift-2 = 'move-node-to-workspace 2'
  alt-shift-3 = 'move-node-to-workspace 3'
  alt-shift-4 = 'move-node-to-workspace 4'
  alt-shift-5 = 'move-node-to-workspace 5'
  alt-shift-6 = 'move-node-to-workspace 6'
  alt-shift-7 = 'move-node-to-workspace 7'
  alt-shift-8 = 'move-node-to-workspace 8'
  alt-shift-9 = 'move-node-to-workspace 9'

  # Window focus (vim-style navigation)
  alt-h = 'focus left'
  alt-j = 'focus down'
  alt-k = 'focus up'
  alt-l = 'focus right'

  # Window moving within workspace
  alt-shift-h = 'move left'
  alt-shift-j = 'move down'
  alt-shift-k = 'move up'
  alt-shift-l = 'move right'

  # Layout modes
  alt-f = 'layout floating tiling'  # Toggle floating
  alt-t = 'layout tiles'             # Tiles layout
  alt-s = 'layout accordion'         # Accordion layout

  # Resize mode
  alt-r = 'mode resize'
  
  # Fullscreen toggle (Hyprland-like)
  alt-m = 'fullscreen'

# ─────────────────────────────────────────────────────────────────────
# Resize Mode - Smooth Window Resizing
# ─────────────────────────────────────────────────────────────────────

[mode.resize.binding]
  esc = 'mode main'
  enter = 'mode main'
  
  # Resize with vim keys
  h = 'resize width -50'
  l = 'resize width +50'
  k = 'resize height -50'
  j = 'resize height +50'
  
  # Balance all windows
  b = 'balance-sizes'
  
  # Smart resize
  minus = 'resize smart -50'
  equal = 'resize smart +50'

# ─────────────────────────────────────────────────────────────────────
# Application-Specific Window Rules
# ─────────────────────────────────────────────────────────────────────

[[on-window-detected]]
  if.app-id = 'com.discord.Discord'
  run = 'move-node-to-workspace 2'

[[on-window-detected]]
  if.app-id = 'com.microsoft.VSCode'
  run = 'move-node-to-workspace 3'

[[on-window-detected]]
  if.app-id = 'app.zen-browser.zen'
  check-further-callbacks = true
  run = ['move-node-to-workspace 2']

# ─────────────────────────────────────────────────────────────────────
# Monitor Assignment
# ─────────────────────────────────────────────────────────────────────

[workspace-to-monitor-force-assignment]
  1 = 1
  2 = 1
  3 = 1
  4 = 1
  5 = 1
  6 = 1
  7 = 1
  8 = 1
  9 = 1

