# Start Aerospace at login
start-at-login = true

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# Start sketchybar when starting aerospace
after-startup-command = ['exec-and-forget sketchybar']

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE'
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Window workspace assignments
on-window-detected = 'move-node-to-workspace 1'

[mode.main.binding]
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# You can uncomment this line to open up terminal with alt + enter shortcut
# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

alt-enter = 'workspace 1'
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

# Window movement
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

# Window focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Window moving within workspace
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Layout modes
alt-f = 'layout floating tiling'
alt-t = 'layout tiles vertical horizontal'
alt-s = 'layout v_accordion h_accordion'

# Resize mode
alt-r = 'mode resize'

[mode.resize.binding]
escape = 'mode main'
enter = 'mode main'
h = 'resize smart -50'
j = 'resize smart +0 +50'
k = 'resize smart +0 -50'
l = 'resize smart +50'

# Special settings for workspace 1
[[workspace]]
id = 1
on-space-enter = 'sketchybar --trigger aerospace_workspace_change WORKSPACE=1'

[[workspace]]
id = 2
on-space-enter = 'sketchybar --trigger aerospace_workspace_change WORKSPACE=2'

[[workspace]]
id = 3
on-space-enter = 'sketchybar --trigger aerospace_workspace_change WORKSPACE=3'

[[workspace]]
id = 4
on-space-enter = 'sketchybar --trigger aerospace_workspace_change WORKSPACE=4'

[[workspace]]
id = 5
on-space-enter = 'sketchybar --trigger aerospace_workspace_change WORKSPACE=5'

[[workspace]]
id = 6
on-space-enter = 'sketchybar --trigger aerospace_workspace_change WORKSPACE=6'

[[workspace]]
id = 7
on-space-enter = 'sketchybar --trigger aerospace_workspace_change WORKSPACE=7'

[[workspace]]
id = 8
on-space-enter = 'sketchybar --trigger aerospace_workspace_change WORKSPACE=8'

[[workspace]]
id = 9
on-space-enter = 'sketchybar --trigger aerospace_workspace_change WORKSPACE=9'

[[workspace]]
id = 10
on-space-enter = 'sketchybar --trigger aerospace_workspace_change WORKSPACE=10'

# App specific workspace assignments
[[on-window-detected]]
if.app-id = 'com.discord.Discord'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.github.delocalized.Kitty'
run = 'move-node-to-workspace 1'

[workspace-to-monitor-force-assignment]
1 = 1
2 = 1
3 = 1
4 = 1
5 = 1
6 = 1
7 = 1
8 = 1
9 = 1
10 = 1

